---
apps:
  - name: juice-shop
    image: bkimminich/juice-shop
    ports: 3000:3000
    state: started

  - name: WebGoat-8.0
    image: webgoat/goatandwolf
    ports:
      - 8080:8080
      - 9090:9090
    state: started
