version: "3.8"
services:
  0xffsec-dojo:
    build: ./dojo/
    ports:
      - "80:80"
  web-dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "2000:80"
  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"
  webgoat:
    image: webgoat/goatandwolf
    ports:
      - "4000:8080"
      - "4001:9090"
