---
apps:
  - name: 0xffsec-webdojo
    image: 0xffsec-dojo
    ports: 80:80
    state: started

  - name: web-dvwa
    image: vulnerables/web-dvwa
    ports: 2000:80
    state: started

  - name: juice-shop
    image: bkimminich/juice-shop
    ports: 3000:3000
    state: started

  - name: WebGoat-8.0
    image: webgoat/goatandwolf
    ports:
      - 4000:8080
      - 4001:9090
    state: started
