---
apps:
  - name: web-dvwa
    image: vulnerables/web-dvwa
    ports: 2000:80
    state: started

  - name: juice-shop
    image: bkimminich/juice-shop
    ports: 3000:3000
    state: started

  - name: WebGoat-8.0
    image: webgoat/goatandwolf
    ports:
      - 4000:9090
      - 4001:8080
    state: started
