---
- hosts: all
  become: yes
  vars_files:
    - ../applications.yml

  roles:
    - geerlingguy.docker

  tasks:
    - name: Ensure Pip is installed.
      package:
        name: python-pip
        state: present

    - name: Install Docker Module for Python.
      pip:
        name: docker

    - name: Build Dojo Container.
      docker_image:
        name: webdojo
        build:
          path: ../webdojo/

    - name: Create Dojo Container
      docker_container:
        name: webdojo
        image: webdojo
        state: started
        ports: 80:8080

    - name: Create App Containers.
      docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        ports: "{{ item.ports }}"
        state: "{{ item.state }}"
      with_items: "{{ apps }}"
