---
- hosts: all
  become: yes
  vars_files:
    - applications.yml

  roles:
    - geerlingguy.docker

  tasks:
    - name: Install packages.
      package:
        name:
          - python-pip
        state: present

    - name: Install Python modules.
      pip:
        name:
          - docker

    - name: Build SPA container.
      docker_image:
        build:
          path: ../dojo/
        name: dojo
        source: build

    - name: Create SPA container.
      docker_container:
        image: dojo
        name: dojo
        ports: 80:80
        state: started

    - name: Create applications containers.
      docker_container:
        image: "{{ item.image }}"
        name: "{{ item.name }}"
        ports: "{{ item.ports }}"
        state: "{{ item.state }}"
      with_items: "{{ apps }}"
